version: "3.9"

services:
  gs1:
    build: ./game-service
    restart: always
    ports:
      - "3030:9000"
    depends_on:
      - battle
  gs2:
    build: ./game-service
    restart: always
    ports:
      - "3031:9000"
    depends_on:
      - battle
  battle:
    build: ./battle-service
    restart: always
    ports:
      - "8080:8080"
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8880:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - gs1
      - gs2
